# Fallback editor hints. Label export replaces this file with project-specific names.
from typing import Any, List, Optional, Protocol, Tuple, Union

StageName = str
InfoName = str
ControlName = str
ClickTarget = Union[ControlName, Tuple[float, float], List[float]]


class GameWorker(Protocol):
    current_stage: Optional[StageName]

    def get_info(self, area_name: InfoName) -> Optional[Any]: ...
    def click(self, btn: ClickTarget, x_bias: float = 0, y_bias: float = 0, **kwargs: Any) -> Any: ...
    def tap_single(self, btn: ClickTarget, **kwargs: Any) -> Any: ...
    def change_stage(self, stage_name: StageName) -> Any: ...
    def refresh_frame(self, settle: bool = True) -> Any: ...
    def frame_log(self, message: str, **kwargs: Any) -> Any: ...
    def stop(self) -> Any: ...
